src/core/mpu/config.c

This PR fixes the mapping of the shared memory.
With MPU this must have a 1-to-1 typology, as the ipc base address must be the same as the sh_mem base address
Signed-off-by: Afonso Santos <afomms@gmail.com>

fix(mpu): initializing sh_mem place_phys flag for 1-to-1 mapping

---

src/arch/armv8/armv8-r/aarch32/boot.S
src/arch/armv8/armv8-r/aarch64/boot.S
src/arch/armv8/inc/arch/sysregs.h

This PR allows the exceptions on the EL2 to be taken on the A32 state, as the TE bit is cleared.
The reset value of the TE bit from HSCTLR is implementation defined.
Signed-off-by: Afonso Santos <afomms@gmail.com>

fix(aarch32): clear TE bit to take exceptions on A32 state

---

src/lib/printk.c

The current printk has an error when processing negative print, displaying a very large value. For example, print(%d, -1) is displayed as 4294967295 because the unsigned data type is used when processing this type.
Signed-off-by: JianlongCao <caojianlong@outlook.com>

Fix the printk with error negative digits display

---

scripts/platform_defs_gen.c
src/arch/armv8/aarch32/boot.S
src/arch/armv8/aarch64/boot.S
src/arch/riscv/boot.S
src/core/inc/platform.h
src/platform/fvp-r/fvpr_desc.c

Most platforms start with only a single CPU which is then responsible for waking up others, but this is not the case for the newer Arm cortex-R where every CPU wakes up in unison. Because of this, Bao employed a lottery that made use of atomic load/store exclusive (arm) and load-acquire/store-conditional (riscv) instructions to select the master CPU that will subsequently coordinate system initialization. This happens right at the start of execution before MMU/MPU is enabled. This is a problem because the used atomic instructions might only work with translation enabled in Arm platforms or if the used atomic data is part of a non-reservable PMA region in RISC-V, which could result in multiple CPUs assuming they were the boot master.
To circumvent this problem, this PR first reverts the …

Update CPU master selection

---

src/arch/armv8/inc/arch/hypercall.h
src/core/hypercall.c

The current multi-arch implementation does not include RISC-V A0 register when running Bao on top of a RISC-V arch. A0 contains the ipc_id and it is not passed to the ipc_ipercall() function causing possible errors due to the right argument missing.
To fix this, the HYPCALL_ARG_REG(ARG) now starts with offset 0 (now A0 is the first register considered for RISC-V), but then the same interface function must be changed for ARM (by adding +1 to the updated offset).
To improve readability and avoid misunderstandings, the argument retrieved by A0 in RISC-V and by X1 in ARM is now called ipc_id.

fix(hypercall/risc-v): don't exclude A0 register from args retrieval in hypercall()

---

src/arch/armv8/aarch32/boot.S
src/arch/armv8/aarch64/boot.S

Following contributions:
- remove trailling whitespaces
- use Load-acquire, Store-release to ensure correct sync up at initialization between PEs for both aarch64 and aarch32
Signed-off-by: JorgeMVP <jorgepereira89@gmail.com>

ARMv8 boot: improvement

---

Makefile
src/core/inc/types.h
src/core/ipc.c

This PR is mainly for fixing some of the "relevant typos" (and related whitespaces) in the code base.
The important one is the one inside the Makefile which also avoid a possible bug.
The others are more related to the comprehension and "raw documentation" of the code.

Typos fixing and trailing whitespace removal

---

src/lib/bitmap.c

This PR fixes the stop condition on the _bitmap_count_consecutive_ function.
The fix assures that the cycle finishes before accessing one position after the bitmap size

fix(lib/bitmap): count consecutive limit check

---

src/arch/riscv/vm.c

Fix vplic_init call in riscv/vm.c to initialize the vplic with config's plic base instead platform's.
I have tested it in QEMU running Linux to ensure that the modifications perform as intended. To guarantee this, I configured the Linux VM to access the PLIC at address 0xd000000 instead of the physical address 0xc000000. With these modifications, it worked successfully.

fix(riscv/vm): fix vplic_init call 

---

src/arch/armv8/inc/arch/vm.h
src/arch/riscv/inc/arch/vm.h

I believe that the correct type for interrupt id here should be irqid_t.

fix(*/vm.h): change irq type in irq inject funcs

---

src/arch/armv8/aarch64/boot.S
src/arch/armv8/asm_defs.c

In armv8, the platform's cluster information is used in the boot assembly code to linearize the CPU ID from Arm's hierarchical "affinity ID". However,  the code assumed byte-width entries in the `cluster_num` array, which were, in fact, of `size_t` type, which is a machine-word-sized type. In the past, the type was indeed `uint8_t` but was changed recently.
This PR fixes this issue and generates a macro with the type size used by a pre-processor assert to prevent this issue from resurfacing if the type is changed again in the future.

fix(armv8/aarch64): assert 'cluster_num' type size in asm code 

---

src/arch/armv8/gicv2.c
src/arch/armv8/vgic.c
src/arch/riscv/sbi.c
src/core/inc/vm.h
src/core/mmu/mem.c
src/lib/inc/bit.h

In order to use some of the operations defined for the `bitmap_t*` type, some functions were casting integer types pointers to `bitmap_t*`.  This is not the best practice and was causing some issues with the latest GCC versions, as pointed out in #78.
This PR fixes this issue by refactoring these operations using simple bit manipulation functions available in *bit/util/bit.h*. However, it was still needed to add the `bit_ffs` and `bit_count` functions so that all functionality needed was available.

Fix forced integer to bitmap casts

---

src/arch/armv8/aarch32/inc/arch/spinlock.h
src/arch/armv8/aarch64/inc/arch/spinlock.h

This is needed to avoid that compiler optimization reorder critical section instructions across the lock/unlock limits.

fix(arm/spinlock): add compiler memory barrier to inline asm

---

src/arch/armv8/inc/arch/platform.h
src/arch/armv8/inc/arch/vm.h

The platform structure is the same for Arm architecture, which includes systems with MMU and/or MPU.
It is necessary to not include the SMMU struct, in systems with MPU, as the type of data used on that struct is only defined on the smmuv2 header file. 
This PR addresses the compilation error due to the smmuv2 files not being included on the MPU.

fix(platform): only add smmu struct when using mmu

---

src/arch/riscv/interrupts.c

When handling software interrupts (i.e., IPIs) in risc-v we must clear the interrupt pending bit before handling the interrupt. The IPI handler (i.e., cpu msg handler) loops through the event queue until it sees no more events which solves the issue of two superimposed IPIs triggered before or while the handler runs. However, currently, if a new IPI becomes pending between the time the cpu_msg_handler ends and we clear the "software interrupt pending bit" we can loose an IPI, and a cpu message event will go unhandled until a third IPI arrives.

fix(riscv): fix order of clear software pending

---

Makefile

This is meant to provide a way to, by inspecting the executable object file, discover Bao's version. I'm wondering if you should actually embed it as a string in the binary so that this can also be discovered just by inspecting the image.

feat: add version symbol to final object file

---

.github/workflows/base.yml
.github/workflows/build-arm.yaml
.github/workflows/build-riscv.yaml
.gitignore
.gitmodules
Makefile
README.md
configs/null/config.c

This PR introduces the bao-ci infrastructure as a git submodule and instantiates and creates Github actions for basic checks such as:
- all files have the correct license and copyright info;
- git commit message linting to enforce conventional commit convention;
- compiles without errors for a set of representative platforms for both arm and risc-v architectures.
It adds status stickers to the readme file that display the status of the build checks. You can check out how this looks [here](https://github.com/bao-project/bao-hypervisor/tree/feat/ci).

Introduce CI and basic checks

---

src/arch/armv8/gic.c
src/arch/riscv/iommu.c
src/arch/riscv/sbi.c
src/core/inc/interrupts.h
src/core/interrupts.c
src/core/vm.c

This PR enhances the interrupt reservation functions to prevent race conditions during the reservation process. It comprises the following changes:
1. Added a spinlock to ensure synchronized access to the critical section, preventing race conditions. The original code lacked this synchronization, potentially leading to issues. The spinlock now ensures only one thread can access the critical section at a time, resolving the race condition (https://github.com/bao-project/bao-hypervisor/commit/196a404e58dac8ba93f08b24b06360abe5f39a8e);
2. Introduced a boolean return value to indicate the success of interrupt reservation. This provides a more detailed assessment of interrupt assignment status, aiding in error handling (https://github.com/bao-project/bao-hypervisor/commit/fc2029b8e9dc294ef4e2bb …

fix(irq): prevent interrupt reservation and improve error handling

---

src/arch/riscv/sbi.c

Right now, the sbi rfence implementation only supports 64 harts, so the hart mask has to be rectified for always base 0 and return error if an with hart id >= 64 is being targeted. Both this check and the hart adjusment were being incorrectly performed.
This issue was detected by @D3boker1.

fix(riscv/sbi): rfence hart mask adjustment and check

---

src/arch/armv8/aarch32/aborts.c
src/arch/armv8/aarch64/aborts.c
src/arch/riscv/sync_exceptions.c
src/core/console.c
src/core/inc/bao.h
src/core/inc/console.h
src/core/init.c
src/lib/inc/printk.h
src/lib/printk.c
src/platform/drivers/8250_uart/8250_uart.c
src/platform/drivers/8250_uart/inc/drivers/8250_uart.h
src/platform/drivers/nxp_uart/inc/drivers/nxp_uart.h
src/platform/drivers/nxp_uart/nxp_uart.c
src/platform/drivers/pl011_uart/inc/drivers/pl011_uart.h
src/platform/drivers/pl011_uart/pl011_uart.c
src/platform/drivers/sbi_uart/inc/drivers/sbi_uart.h
src/platform/drivers/sbi_uart/sbi_uart.c
src/platform/drivers/zynq_uart/inc/drivers/zynq_uart.h
src/platform/drivers/zynq_uart/zynq_uart.c

The quality of the previous printk implementation was less than desirable. This PR introduces a new improved, and more robust printk implementation that allows to print strings larger than the allocated print buffers and also adds the "format printf" attribute so that incorrect type identifiers in the format string are detected at compile-time.

New improved printk implementation

---

.github/workflows/build-riscv.yaml
Makefile
scripts/arch/riscv/platform_defs_gen.c
scripts/platform_defs_gen.c
src/arch/riscv/aclint.c
src/arch/riscv/arch.mk
src/arch/riscv/inc/arch/aclint.h
src/arch/riscv/inc/arch/interrupts.h
src/arch/riscv/inc/arch/platform.h
src/arch/riscv/interrupts.c
src/arch/riscv/objects.mk
src/platform/qemu-riscv64-virt/inc/plat/platform.h
src/platform/qemu-riscv64-virt/platform.mk
src/platform/qemu-riscv64-virt/virt_desc.c

Features:
- IPIs sent via ACLINT instead of SBI ECALLs
Notes:
Linux -> https://github.com/avpatel/linux/tree/riscv_aclint_v5
QEMU -> 7.2 with flag _-M aclint=on_

RISC-V ACLINT Support

---

src/arch/riscv/vm.c
src/arch/riscv/vmm.c

This PR centralizes the enabling of the RISCV sstc extension in the vmm architectural initialization function. It also adds the sanity checking that the extension is effectively present if the hypervisor was configured to used it (via a platform-defined macro).
Depends on #106

Refactor riscv sstc ext check

---

src/platform/drivers/8250_uart/inc/drivers/8250_uart.h
src/platform/drivers/nxp_uart/inc/drivers/nxp_uart.h

Add missing uart_putc function prototype to 8250_uart.h and nxp_uart.h files.

fix(plat/drivers): add missing uart_putc function prototype

---

src/arch/armv8/inc/arch/gic.h

According to the specification, if the value of this fieldis N, the maximum SPI INTID is 32(N+1)-1.

fix(gicd): fix calculation of gic's number of irqs

---

src/core/mmu/vmm.c
src/core/vmm.c

First a fence was required to enforce the dependency on `install_info_ready` being set calling vmm_vm_install as there is no real data dependency.
Second, we move the write fence which ensures the write to the page table is visible to within the install function. It is it responsibility to ensure it returns with its effects visible.

fix(core/vmm): fixe use of fences on VMM install

---

src/arch/armv8/armv8-a/inc/arch/smmuv2.h

This pull request addresses an issue in the SMMUv2 struct definition (`smmu_cntxt_hw`) where `PMEVCNTRm` and `PMEVTYPERm` were incorrectly defined as single 32-bit registers, when in fact, they are arrays of 15 positions of 32-bit registers each. This fix ensures that the struct accurately matches the smmuv2 specification of these registers within the SMMU context hardware.

fix(smmuv2): fix smmu_cntxt_hw struct

---

src/arch/armv8/inc/arch/gic.h
src/arch/armv8/vgic.c

According to GIC architecture specification, GICH_MISR[2] is called LRENP, which represents list register entry not present maintenance interrupt.

fix(armv8/gic): correct GICH_MISR_LRENP

---

src/core/inc/ipc.h
src/core/inc/shmem.h
src/core/ipc.c
src/core/objects.mk
src/core/shmem.c
src/core/vm.c
src/core/vmm.c

This patch relocates the initialization and shared memory access steps from the hardcoded settings in the existing IPC file to a generic shared memory file. Previously, the code assumed the existence of only one object working with the shared memory (ipc). With this update, the system is now prepared for future versions where multiple objects can be added and working with the shared memory.

feat(core/shmem): move shared memory logic to dedicated source file

---

src/arch/armv8/armv8-a/aarch32/inc/arch/bao.h
src/arch/armv8/armv8-a/aarch64/inc/arch/bao.h
src/arch/riscv/inc/arch/bao.h
src/core/mmu/vmm.c

The level of page table where entries are shared for aarch32 is lvl 1. By resharing the lvl 0 pte, this was causing erroneous mappings on secondary cores.
Depends on https://github.com/bao-project/bao-hypervisor/pull/114

Fix aarch32 vm install

---

src/arch/armv8/armv8-r/mpu.c

Fix a bug in obtaining mem attributes for an mpu region

fix/arm8-r: mpu entry attributes

---

Makefile

If this reposiroty is not cloned with '--recursive', the ci subdmoudle will not be prenset which will result in any invocation of make to fail. This modification allows that if the ci submodule is not present, it will simply be ignored and typical make calls for building the hypervisor will continue normally.

Allow for ci submodule not be present

---

src/arch/riscv/arch.mk
src/arch/riscv/boot.S
src/arch/riscv/inc/arch/bao.h
src/arch/riscv/inc/arch/csrs.h
src/arch/riscv/inc/arch/page_table.h
src/arch/riscv/interrupts.c
src/arch/riscv/iommu.c
src/arch/riscv/irqc/plic/vplic.c
src/arch/riscv/mem.c
src/arch/riscv/page_table.c
src/arch/riscv/relocate.S
src/arch/riscv/sbi.c
src/arch/riscv/vm.c
src/platform/qemu-riscv32-virt/inc
src/platform/qemu-riscv32-virt/objects.mk
src/platform/qemu-riscv32-virt/platform.mk
src/platform/qemu-riscv32-virt/virt_desc.c
src/platform/qemu-riscv64-virt/virt_desc.c

This PR introduces support for RV32. Because the way the instruction set is written the difference is not much when comparing to RV64. The main areas of modification are:
- modifying assembly instructions that used 64-bit load/store directly by the LOAD/STORE macro which translates to either ld/st or lw/sw depending on if we are targetting RV64 or RV32, respectively;
- support for the sv32 translation mode. This also requires adapting the boot code where the bootstrap page-tables are built manually.
- adapt CSR access to CSRs that have a H variant (e.g., henvcfg, henvcfgh), and other small related issues;
- fix small issues that assumed 64-bit literals.
The PR also includes support for qemu-system-riscv32 virt machine, which is essentially a wrapper over the 64-bit variant.
The main issue …

Add support for 32-bit RISC-V

---

src/core/vm.c

This commit relocates the vCPU active flag assignment from the run method to the vCPU initialization method.
Additionally, it introduces a logic check within the run method to verify whether the vCPU should be executed.

fix(core/vm): enabled the utilization of the vcpu active flag

---

src/arch/armv8/aarch32/inc/arch/subarch/sysregs.h

The changes in commit eb64e58637b9ed8e52a907496052f40f6e7f5d25 prevented bao from executing in fvp-a-aarch32.
This PR reverts the modifications that caused the error.

fix(sysreg): Fix generation of ccsdr_el1 assessors

---

src/core/ipc.c

The IPC module was injecting the IPC object interrupt as an hardware interrupt by default using `vcpu_inject_hw_irq`. However, this interrupt is purely virtual since it does not have a counterpart in hardware and the way bao handles the two kinds of interrupts is different, especially on the arm architecture.
This PR fixes it by calling the more generic `vcpu_inject_irq` which internally decides if it should inject it as a virtual interrupt or virtual.

fix(ipc): inject non-hw interupt

---

src/arch/armv8/aarch32/inc/arch/subarch/sysregs.h

The usage of `unsigned long long` for both variables may introduce unexpected values in the OR operation in the return statement, as the `_temp`  variable is not guaranteed to be initialized to 0.

fix(aarch32/sysregs): fix the 64-bit register read function

---

src/arch/riscv/sbi.c

This PR fixes a couple return values on the SBI code.
First, when the call was not supported this was being returned in value, not error.
Then, the hypercall specific error code was being returned as an sbi error. However, it is best to maintain the error code as a standard sbi return value and return the bao-specific hypercall return in the value field.

Fix RISC-V SBI return values

---

src/arch/riscv/inc/arch/csrs.h
src/arch/riscv/irqc/aia/imsic.c

The PR https://github.com/bao-project/bao-hypervisor/pull/117 introduced some compiling errors for riscv32 builds. 
This PR fixes those errors, which were related to using 64-bit literals for operations/functions that needed 32-bit values.

Fix(rv32_conversions): Fix errors with literal sizes

---

src/arch/riscv/sync_exceptions.c

This PR fixes an issue identified in #188 where the address for trapped byte and halfword accesses did not result in the correct trapped address because the two lower order bits were not retrieved from stval.

fix(riscv): add low order bits to faulting address

---

src/core/remio.c

This PR fixes the method responsible for checking pending Remote I/O requests by adding the missing `!` operator to the `list_empty` call.

fix(core/remio): add missing operator to check pending requests

---

src/core/mmu/mem.c

fix(mem): correctly allocate colored pages
Fixes Issue #199

fix(mem): correctly allocate colored pages

---

src/core/inc/objpool.h

Small PR to mark `objpool_get_by_id` as `static inline` to ensure the function is always available in translation units that use it. This prevents linker errors at optimization level 0, where the compiler will throw an undefined reference error regarding that symbol.

fix(objpool): mark objpool func as static to avoid missing symbol at O0

---

src/core/mpu/mem.c

The subtraction happens after the cast. To fix this, cast the result of the subtraction, instead.

fix(mem): fix size calculation typo

---

src/arch/armv8/aarch32/inc/arch/spinlock.h
src/arch/armv8/aarch64/inc/arch/spinlock.h
src/arch/armv8/vgicv2.c
src/arch/armv8/vgicv3.c
src/arch/armv8/vm.c
src/arch/riscv/inc/arch/spinlock.h
src/arch/riscv/irqc/aia/vaplic.c
src/arch/riscv/irqc/plic/vplic.c
src/core/mem.c
src/core/mpu/mem.c
src/core/objpool.c
src/core/shmem.c
src/core/vm.c
src/core/vmm.c

This PR adds missing initialization of spinlocks across the source code.
Uninitialized control structures are a potential cause of random behavior issues.
The PR also deletes the unused `spinlock_init` function, as spinlock initialization in Bao is done via the `SPINLOCK_INITVAL` macro.

Add missing spinlock initializations

---

src/core/mem.c

This PR fixes the bitmap_size calculation. Previously, we were calculating the bitmap size in bytes but treating it as the number of pages, which led to over-allocation of bitmap memory. The fix properly converts bitmap size to pages using the `NUM_PAGES() `macro.

fix(mem): fix calculation of root bitmap num pages

---

src/core/inc/mem.h
src/core/mem.c
src/core/mmu/mem.c
src/core/mpu/mem.c

This PR fixes the calculation of the root pool's bitmap size.
The expression `root_pool->size` in the `root_pool_set_up_bitmap` function was being mistakenly interpreted as the size of the root pool in **bytes**, when it is actually the size of the root pool in **number of pages**.
To avoid further misunderstandings, this PR also changes the name of the `struct page_pool.size` field to `num_pages`

fix(mem): fix root pool bitmap size

---

scripts/platform_defs_gen.c
src/core/mem.c
src/core/objpool.c
src/lib/inc/bitmap.h

This pull request refactors the memory bitmap allocation logic to use a preallocated bitmap pool. We introduce a global bitmap pool and update relevant functions to allocate bitmaps from this pool instead of allocating memory dynamically. With this PR we optimize the use of MPU regions in MMU-less platforms, as the global bitmap is allocated in the .bss section as part of the hyp image.
To calculate the size of the global bitmap pool based on platform regions, we added `PLAT_BITMAP_POOL_SIZE` in `scripts/platform_defs_gen.c`.

feat/static-bitmaps: change bitmaps to be statically allocated

---

src/arch/armv8/armv8-r/aarch32/boot.S
src/arch/armv8/armv8-r/mpu.c

This PR fixes the missing of an instruction synchronization barrier after enabling the MPU in ARMv8-R architectures. This is mandatory to any change to system registers as mentioned in the architectural reference manual. 
> An ISB instruction ensures that all instructions that come after the ISB instruction in program order are fetched from the
cache or memory after the ISB instruction has completed. Using an ISB ensures that the effects of context-changing
operations executed before the ISB are visible to the instructions fetched after the ISB instruction. Examples of
context-changing operations that require the insertion of an ISB instruction to ensure the effects of the operation are
visible to instructions fetched after the ISB instruction are:
•Completed cache and TLB maintenance …

fix(mpu): add inst sync barrier to mpu enable
